Repository wellwelwel/poku, pull requests merged in 2024-08, with the labels that each got.

#633 feat: add `.todo` helper for `describe`, `it`, and `test`
  .github/workflows/ci_coverage-windows.yml
  CONTRIBUTING.md
  README.md
  fixtures/final-results/skip-and-todo/skip.test.ts
  fixtures/final-results/skip-and-todo/todo.test.ts
  fixtures/final-results/skip-todo-and-failure/failure.test.ts
  fixtures/final-results/skip-todo-and-failure/skip.test.ts
  fixtures/final-results/skip-todo-and-failure/todo.test.ts
  fixtures/final-results/skip/skip.test.ts
  fixtures/final-results/todo/todo.test.ts
  fixtures/schemas/options.json
  src/bin/index.ts
  src/configs/poku.ts
  src/modules/essentials/poku.ts
  src/modules/helpers/describe.ts
  src/modules/helpers/exit.ts
  src/modules/helpers/it/core.ts
  src/modules/helpers/it/todo.ts
  src/modules/helpers/list-files.ts
  src/modules/helpers/skip.ts
  src/parsers/output.ts
  src/services/format.ts
  src/services/watch.ts
  test/c8.test.ts
  test/e2e/final-results.test.ts
  test/e2e/ignored-paths.test.ts
  test/integration/describe/todo.test.ts
  test/integration/it/it.test.ts
  test/integration/it/todo.test.ts
  test/integration/test/test.test.ts
  test/integration/test/todo.test.ts
  test/unit/wait-for/wait-for-trhows.test.ts
  website/README.md
  website/docs/documentation/helpers/startScript.mdx
  website/docs/documentation/helpers/startService.mdx
  website/docs/documentation/helpers/todo.mdx
  website/docs/documentation/poku/config-files.mdx
  website/docs/documentation/poku/include-files.mdx
  website/docs/examples/local-server.mdx
  website/docs/philosophy.mdx
  website/docs/tutorials/beginner.mdx
  website/docs/tutorials/cross-platform.mdx
  website/docs/tutorials/good-practices.mdx
  website/sidebars.ts
Labels: boilerplate

#634 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#635 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#637 perf: improve concurrency defaults (inspired by Jest definitions)
  README.md
  benchmark/README.md
  benchmark/benchmark.js
  src/bin/index.ts
  src/services/run-tests.ts
  website/docs/comparing.mdx
  website/docs/documentation/poku/options/concurrency.mdx
Labels: performance

#636 chore(main): release 2.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#639 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#640 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#643 feat: add `--version` command line option
  package.json
  src/bin/index.ts
  src/bin/watch.ts
  src/configs/poku.ts
  src/modules/index.ts
  test/integration/import.test.ts
  tools/build/version.ts
Labels: cli

#645 feat: add `--list-files` command line option
  src/bin/index.ts
  website/docs/documentation/helpers/list-files.mdx
Labels: needs docs, cli, list files

#646 feat: allow multiple args and types to `log` helper
  src/modules/helpers/log.ts
Labels: output

#644 chore(main): release 2.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#654 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#655 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#657 fix: sort list of the file paths emitted by `--list-files`
  src/bin/index.ts
Labels: cli, list files

#656 docs: add pt-BR translation to Poku and Helpers sections
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/assert/index.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/before-after-each/in-code.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/before-after-each/per-file.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/containers.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/describe.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/env.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/it.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/skip.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/startScript.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/test.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/config-files.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/options/concurrency.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/options/debug.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/options/deno.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/options/fail-fast.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/options/no-exit.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/options/quiet.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/options/watch.mdx
Labels: documentation

#658 chore(main): release 2.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#659 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#660 fix: prevent premature exit of test suites
  src/modules/helpers/exit.ts
Labels: output

#662 fix: prevent premature exit after an assertion failure
  .github/workflows/ci_compatibility-nodejs.yml
  src/builders/assert.ts
  src/modules/essentials/assert.ts
  src/modules/essentials/poku.ts
  src/modules/essentials/strict.ts
  src/services/assert.ts
  src/services/write.ts
  test/compatibility/node-09.test.ts
  test/compatibility/node-11.test.ts
  test/compatibility/node-13.test.ts
  test/compatibility/node-15.test.ts
  test/compatibility/node-17.test.ts
  test/compatibility/node-19.test.ts
  test/compatibility/node-21.test.ts
  test/docker/docker-compose.yml
  test/docker/node/09.Dockerfile
  test/docker/node/11.Dockerfile
  test/docker/node/13.Dockerfile
  test/docker/node/15.Dockerfile
  test/docker/node/17.Dockerfile
  test/docker/node/19.Dockerfile
  test/docker/node/21.Dockerfile
Labels: assert, output

#661 chore(main): release 2.4.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#664 fix(Deno): fix `process` interoperability after `v2.4.2`
  src/services/assert.ts
Labels: deno, assert

#663 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#666 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#665 chore(main): release 2.4.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#667 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#668 fix: make output less verbose
  src/services/format.ts
Labels: output

#676 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#677 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#681 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#682 fix: propagate exit code when a failure occurs with `--fail-fast`
  src/services/run-tests.ts
  test/c8.test.ts
  test/e2e/fail-fast.test.ts
Labels: test runner, processes

#669 chore(main): release 2.4.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#683 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#684 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#694 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#695 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#689 fix(waitForPort): ensure process exit after Bun `v1.1.23`
  .github/workflows/ci_compatibility-bun.yml
  src/modules/helpers/wait-for.ts
Labels: bun

#688 feat(cli): support camelCase flags (deprecate kebab-case flags)
  package.json
  src/bin/index.ts
  src/bin/watch.ts
  src/parsers/get-arg.ts
  src/parsers/to-dynamic-case.ts
  src/services/run-tests.ts
  test/__fixtures__/e2e/no-tests/.gitkeep
  test/c8.test.ts
  test/e2e/cli-flags.test.ts
  test/e2e/env-file.test.ts
  test/e2e/fail-fast.test.ts
  test/e2e/watch.test.ts
  test/unit/dynamic-cases.test.ts
  website/docs/documentation/helpers/env.mdx
  website/docs/documentation/helpers/list-files.mdx
  website/docs/documentation/helpers/processes/kill.mdx
  website/docs/documentation/poku/config-files.mdx
  website/docs/documentation/poku/options/deno.mdx
  website/docs/documentation/poku/options/fail-fast.mdx
  website/docs/documentation/poku/options/watch.mdx
  website/docs/tutorials/cross-platform.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/env.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/list-files.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/helpers/processes/kill.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/config-files.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/options/deno.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/options/fail-fast.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/options/watch.mdx
Labels: needs docs, cli

#697 docs(pt-BR): translate all remaining documentation
  website/docs/examples/cases/complexity-no-exit.mdx
  website/docs/tutorials/beginner.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/comparing.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/config-files.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/include-files.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/documentation/poku/options/concurrency.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/examples/browser/DOM.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/examples/browser/react.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/examples/cases/complexity-no-exit.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/examples/cjs-esm.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/examples/mock/cjs.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/examples/mock/esm.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/examples/promises.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/philosophy.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/tutorials/beginner.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/tutorials/cross-platform.mdx
  website/i18n/pt-BR/docusaurus-plugin-content-docs/current/tutorials/good-practices.mdx
Labels: documentation

#698 ci(website): trigger publish workflow dispatch
  .github/workflows/cd_docs-deploy.yml
  .github/workflows/cd_publish.yml
Labels: website

#699 feat(cli): enforce flags validation
  biome.jsonc
  src/bin/enforce.ts
  src/bin/index.ts
  test/e2e/cli-ensure-flags.test.ts
  website/docs/documentation/poku/options/enforce.mdx
Labels: cli

#696 chore(main): release 2.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#700 ci(website): fix workflow dispatch permission
  .github/workflows/cd_publish.yml
Labels: website

#702 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#704 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#705 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#706 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#707 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#709 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#715 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#716 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#717 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#719 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies

#720 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#721 chore(website): update dependencies
  website/package-lock.json
  website/package.json
Labels: website, dependencies
